Commit Lecture 4-4
[React.js] 강좌 4-4편: Contact 추가/삭제/수정 기능 구현 | Immutability Helper 적용하기

[# Error]

[./src/index.js] 1.42 KiB {main} [built] [failed] [1 error]
    + 44 hidden modules

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In C:\Users\ysk45\Documents\react-fundamentals\node_modules\babel-preset-stage-0\lib\index.js
    at createDescriptor (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at items.map (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-chain.js:320:26)
    at C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-chain.js:283:7
    at Generator.next (<anonymous>)
    at buildRootChain (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-chain.js:120:29)

=> npm i --save @babel/preset-stage-0
등으로 바꾸어 보았지만

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\Users\ysk45\Documents\react-fundamentals\src\index.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    // Stage 0
    "@babel/plugin-proposal-function-bind",

    // Stage 1
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    ["@babel/plugin-proposal-optional-chaining", { "loose": false }],
    ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }],
    ["@babel/plugin-proposal-nullish-coalescing-operator", { "loose": false }],
    "@babel/plugin-proposal-do-expressions",

    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
   (While processing: "C:\\Users\\ysk45\\Documents\\react-fundamentals\\node_modules\\@babel\\preset-stage-0\\lib\\index.js")
    at _default (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\preset-stage-0\lib\index.js:9:9)
    at C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\gensync-utils\async.js:26:3)
    at Generator.next (<anonymous>)
    at step (C:\Users\ysk45\Documents\react-fundamentals\node_modules\gensync\index.js:254:32)
    at evaluateAsync (C:\Users\ysk45\Documents\react-fundamentals\node_modules\gensync\index.js:284:5)
    at Function.errback (C:\Users\ysk45\Documents\react-fundamentals\node_modules\gensync\index.js:108:7)
    at errback (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\gensync-utils\async.js:70:18)
    at async (C:\Users\ysk45\Documents\react-fundamentals\node_modules\gensync\index.js:183:31)
 @ multi react-hot-loader/patch ./src/index.js main[1]

위와 같은 에러 메시지를 출력하는데, 스테이지 preset 기능을 제거한 모양..
음.. 일단 진행하다가 문제생기면  다시 건드려야할듯 하다.