Commit Lecture 3-3
[React.js] 강좌 3-3편: Hot Module Replacement | React Hot Loader

### 앞서, 이전 강의에서 실행 테스트를 안했었던 관계로, 시작하자마 발생한 에러에 대한 정리를 먼저 하고자 함.

[#Error - 첫번째]
The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli

[# 해결 방법]
npm i webpack-cli -D

[#Error - 두번째]
× ｢wds｣: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
npm ERR! Test failed.  See above for more details.

[# 해결 방법]
webpack.config.js 에서 module의 loaders => rules, babel => babel-loader로 교체
[참고 사이트 : https://webpack.js.org/migrate/3/#module-loaders-is-now-module-rules]

[#Error - 세번째]
[./src/index.js] 1010 bytes {main} [not cacheable] [built] [failed] [1 error]
    + 20 hidden modules

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\ysk45\Documents\react-fundamentals\node_modules\babel-loader\lib\index.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

[# 해결 방법]
npm i @babel/core

[#Error - 네번째]
[./src/index.js] 1.38 KiB {main} [built] [failed] [1 error]
    + 20 hidden modules

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In C:\Users\ysk45\Documents\react-fundamentals\node_modules\babel-preset-es2015\lib\index.js
    at createDescriptor (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at items.map (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at passPerPreset (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\config-descriptors.js:58:104)
    at cachedFunction (C:\Users\ysk45\Documents\react-fundamentals\node_modules\@babel\core\lib\config\caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (C:\Users\ysk45\Documents\react-fundamentals\node_modules\gensync\index.js:244:28)
    at sync (C:\Users\ysk45\Documents\react-fundamentals\node_modules\gensync\index.js:84:14)

[# 해결 방법]
npm i @bable/preset-env @babel/preset-react
설치 후, webpack.config.js에서 module -> rules -> query -> presets의 설정을
presets: ["@babel/preset-env","@babel/preset-react"] 로 교체
필요 여부는 모르겠지만, 바로 아래
plugins: ["react-hot-loader/babel"]도 추가.

<결과>
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    cacheDirectory: true,
                    presets: ["@babel/preset-env","@babel/preset-react"],
                    plugins: ["react-hot-loader/babel"]
                }
            }
        ]
    }

..... 그럼에도 불구하고
localhost:4000에 접속하면
Cannot GET / 페이지 출력....

[# 문제를 찾았다.. public 폴더의 이름을 잘못 썼다...]
( bundle.js 파일을 생성이 되지 않는데 정상인건가? )

일단, 저장과 동시에 페이지 리로딩이 일어나기때문에 state값이 유지가 되지않는다..
버전 차이 때문인지 무슨 수를 써도 똑같이 진행되지는 않아서.. 일단 이부분은 패스..